#FROM jenkins/jenkins:2.176.1
FROM jenkins/jenkins:lts-jdk11

# Distributed Builds plugins
RUN /usr/local/bin/install-plugins.sh ssh-slaves

#Install Git
RUN /usr/local/bin/install-plugins.sh git

# install Notifications and Publishing plugins
RUN /usr/local/bin/install-plugins.sh email-ext
RUN /usr/local/bin/install-plugins.sh mailer
RUN /usr/local/bin/install-plugins.sh slack

# Artifacts
RUN /usr/local/bin/install-plugins.sh htmlpublisher

# UI
RUN /usr/local/bin/install-plugins.sh greenballs
RUN /usr/local/bin/install-plugins.sh simple-theme-plugin

# Scaling
RUN /usr/local/bin/install-plugins.sh kubernetes

USER jenkins
VOLUME /var/jenkins_home

# install Maven
USER root
RUN apt-get update && apt-get install -y maven
USER jenkins
